datasources:
  default:
    url: jdbc:h2:mem:kuaDb;LOCK_TIMEOUT=10000
    driverClassName: org.h2.Driver
    username: 'kuaUser'
    password: 'userPw'

jpa:
  default:
    properties:
      hbm2ddl:
        auto: validate

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - "classpath:kua-notes/h2"
